import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Simple Shared List',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  // eslint-disable-next-line no-undef
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-zinc-800 text-zinc-200  flex flex-col overflow-hidden">
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  )
}
